version: 2

models:
  - name: stg_sensor_data
    description: "Clean staging model for AtmoSync sensor telemetry."

    columns:
      - name: container_id
        tests:
          - not_null

      - name: location
        tests:
          - not_null

      - name: temperature
        tests:
          - not_null

      - name: recorded_at
        tests:
          - not_null
